In [27]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:

data_path = "../data/interim/final_data.csv"

df = pd.read_csv(data_path, parse_dates=["tpep_pickup_datetime"])

In [4]:
df.head()

  tpep_pickup_datetime  Region  Pickups  Avg_pickups
0  2016-01-01 00:00:00       0       57         57.0
1  2016-01-01 00:15:00       0      113         92.0
2  2016-01-01 00:30:00       0      146        120.0
3  2016-01-01 00:45:00       0      162        139.0
4  2016-01-01 01:00:00       0      182        158.0

In [6]:
df.isnull().sum()

tpep_pickup_datetime    0
Region                  0
Pickups                 0
Avg_pickups             0
dtype: int64

* NO Missing Data

In [8]:
df["Day"]=df["tpep_pickup_datetime"].dt.day_of_week
df["Month"]=df["tpep_pickup_datetime"].dt.month

In [9]:
df

       tpep_pickup_datetime  Region  Pickups  Avg_pickups  Day  Month
0       2016-01-01 00:00:00       0       57         57.0    4      1
1       2016-01-01 00:15:00       0      113         92.0    4      1
2       2016-01-01 00:30:00       0      146        120.0    4      1
3       2016-01-01 00:45:00       0      162        139.0    4      1
4       2016-01-01 01:00:00       0      182        158.0    4      1
...                     ...     ...      ...          ...  ...    ...
262075  2016-03-31 22:45:00      29       13         19.0    3      3
262076  2016-03-31 23:00:00      29       43         29.0    3      3
262077  2016-03-31 23:15:00      29       24         27.0    3      3
262078  2016-03-31 23:30:00      29       12         21.0    3      3
262079  2016-03-31 23:45:00      29       23         22.0    3      3

[262080 rows x 6 columns]

* Day and Month are Nominal data so i apply One Hot Encoder

In [10]:
df.set_index("tpep_pickup_datetime",inplace=True)

In [36]:
df

                      Region  Pickups  Avg_pickups  Day  Month
tpep_pickup_datetime
2016-01-01 00:00:00        0       57         57.0    4      1
2016-01-01 00:15:00        0      113         92.0    4      1
2016-01-01 00:30:00        0      146        120.0    4      1
2016-01-01 00:45:00        0      162        139.0    4      1
2016-01-01 01:00:00        0      182        158.0    4      1
...                      ...      ...          ...  ...    ...
2016-03-31 22:45:00       29       13         19.0    3      3
2016-03-31 23:00:00       29       43         29.0    3      3
2016-03-31 23:15:00       29       24         27.0    3      3
2016-03-31 23:30:00       29       12         21.0    3      3
2016-03-31 23:45:00       29       23         22.0    3      3

[262080 rows x 5 columns]

In [37]:
region_grp=df.groupby("Region")

In [13]:
region_grp

In [25]:
pds=[1,2,3,4]

In [38]:
features=region_grp["Pickups"].shift(pds)

In [39]:
features

                      Pickups_1  Pickups_2  Pickups_3  Pickups_4
tpep_pickup_datetime
2016-01-01 00:00:00         NaN        NaN        NaN        NaN
2016-01-01 00:15:00        57.0        NaN        NaN        NaN
2016-01-01 00:30:00       113.0       57.0        NaN        NaN
2016-01-01 00:45:00       146.0      113.0       57.0        NaN
2016-01-01 01:00:00       162.0      146.0      113.0       57.0
...                         ...        ...        ...        ...
2016-03-31 22:45:00        17.0       30.0       31.0       24.0
2016-03-31 23:00:00        13.0       17.0       30.0       31.0
2016-03-31 23:15:00        43.0       13.0       17.0       30.0
2016-03-31 23:30:00        24.0       43.0       13.0       17.0
2016-03-31 23:45:00        12.0       24.0       43.0       13.0

[262080 rows x 4 columns]

In [40]:
features.isnull().sum()

Pickups_1     30
Pickups_2     60
Pickups_3     90
Pickups_4    120
dtype: int64

In [41]:
dfs=pd.concat([df,features],axis=1)

In [42]:
dfs.dropna(how="any",inplace=True)

In [43]:
dfs

,Region,Pickups,Avg_pickups,Day,Month,Pickups_1,Pickups_2,Pickups_3,Pickups_4
tpep_pickup_datetime,,,,,,,,,
2016-01-01 01:00:00,0,182,158.0,4,1,162.0,146.0,113.0,57.0
2016-01-01 01:15:00,0,194,173.0,4,1,182.0,162.0,146.0,113.0
2016-01-01 01:30:00,0,188,179.0,4,1,194.0,182.0,162.0,146.0
2016-01-01 01:45:00,0,185,182.0,4,1,188.0,194.0,182.0,162.0
2016-01-01 02:00:00,0,176,179.0,4,1,185.0,188.0,194.0,182.0
...,...,...,...,...,...,...,...,...,...
2016-03-31 22:45:00,29,13,19.0,3,3,17.0,30.0,31.0,24.0
2016-03-31 23:00:00,29,43,29.0,3,3,13.0,17.0,30.0,31.0
2016-03-31 23:15:00,29,24,27.0,3,3,43.0,13.0,17.0,30.0
2016-03-31 23:30:00,29,12,21.0,3,3,24.0,43.0,13.0,17.0
2016-03-31 23:45:00,29,23,22.0,3,3,12.0,24.0,43.0,13.0

In [33]:
dfs.isnull().sum()

Region         0
Pickups        0
Avg_pickups    0
Day            0
Month          0
Pickups_1      0
Pickups_2      0
Pickups_3      0
Pickups_4      0
dtype: int64

In [44]:
dfs["Month"].value_counts()

Month
3    89280
1    89160
2    83520
Name: count, dtype: int64

* Because it is a time series data so we can't train test split randomly . i break month 1,2 as train and month 3 as test.

In [50]:
train=dfs[dfs["Month"].isin([1,2])].drop(columns=["Month"])

In [52]:
test=dfs[dfs["Month"].isin([3])].drop(columns=["Month"])

In [53]:
train

,Region,Pickups,Avg_pickups,Day,Pickups_1,Pickups_2,Pickups_3,Pickups_4
tpep_pickup_datetime,,,,,,,,
2016-01-01 01:00:00,0,182,158.0,4,162.0,146.0,113.0,57.0
2016-01-01 01:15:00,0,194,173.0,4,182.0,162.0,146.0,113.0
2016-01-01 01:30:00,0,188,179.0,4,194.0,182.0,162.0,146.0
2016-01-01 01:45:00,0,185,182.0,4,188.0,194.0,182.0,162.0
2016-01-01 02:00:00,0,176,179.0,4,185.0,188.0,194.0,182.0
...,...,...,...,...,...,...,...,...
2016-02-29 22:45:00,29,36,53.0,0,51.0,76.0,64.0,80.0
2016-02-29 23:00:00,29,45,50.0,0,36.0,51.0,76.0,64.0
2016-02-29 23:15:00,29,30,42.0,0,45.0,36.0,51.0,76.0
2016-02-29 23:30:00,29,30,37.0,0,30.0,45.0,36.0,51.0
2016-02-29 23:45:00,29,16,29.0,0,30.0,30.0,45.0,36.0

In [54]:
test

,Region,Pickups,Avg_pickups,Day,Pickups_1,Pickups_2,Pickups_3,Pickups_4
tpep_pickup_datetime,,,,,,,,
2016-03-01 00:00:00,0,61,61.0,1,42.0,53.0,64.0,86.0
2016-03-01 00:15:00,0,49,56.0,1,61.0,42.0,53.0,64.0
2016-03-01 00:30:00,0,37,48.0,1,49.0,61.0,42.0,53.0
2016-03-01 00:45:00,0,42,46.0,1,37.0,49.0,61.0,42.0
2016-03-01 01:00:00,0,40,44.0,1,42.0,37.0,49.0,61.0
...,...,...,...,...,...,...,...,...
2016-03-31 22:45:00,29,13,19.0,3,17.0,30.0,31.0,24.0
2016-03-31 23:00:00,29,43,29.0,3,13.0,17.0,30.0,31.0
2016-03-31 23:15:00,29,24,27.0,3,43.0,13.0,17.0,30.0
2016-03-31 23:30:00,29,12,21.0,3,24.0,43.0,13.0,17.0
2016-03-31 23:45:00,29,23,22.0,3,12.0,24.0,43.0,13.0

* Pickup_1 Pickup_2 Pickup_3 Pickup4 are t-i data based on the previous one data i predict the current time.

In [55]:
train_data_path="../data/processed/train_data.csv"
test_data_path="../data/processed/test_data.csv"

In [56]:
train.to_csv(train_data_path,index=True)
test.to_csv(test_data_path,index=True)

In [ ]:
X_train=train.drop(columns=["Pickups"])

y_train=train["Pickups"]
X_test=test.drop(columns=["Pickups"])
y_test=test["Pickups"]

In [60]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_absolute_percentage_error
from sklearn.linear_model import LinearRegression

In [62]:
from sklearn import set_config

set_config(transform_output="pandas")

In [64]:
encoder=ColumnTransformer(
    [
        ("ohe",OneHotEncoder(drop="first",sparse_output=False),["Region","Day"])
    ],
    remainder="passthrough",n_jobs=-1
)

In [65]:
pipeline=Pipeline(
    [
        ("encoder",encoder),
        ("lr",LinearRegression())
    ]
)

In [66]:
pipeline.fit(X_train,y_train)

Pipeline(steps=[('encoder',
                 ColumnTransformer(n_jobs=-1, remainder='passthrough',
                                   transformers=[('ohe',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False),
                                                  ['Region', 'Day'])])),
                ('lr', LinearRegression())])

In [69]:
y_pred_test=pipeline.predict(X_test)
y_pred_train=pipeline.predict(X_train)

In [70]:
train_error=mean_absolute_percentage_error(y_train,y_pred_train)
test_error=mean_absolute_percentage_error(y_test,y_pred_test)

In [71]:
print(f"Train Error : {train_error}")
print(f"Test Error : {test_error}")

Train Error : 0.10155130872260107
Test Error : 0.0857388276235987

# BaseLine Model is Build With error : 8%

# Model Selection

In [73]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.svm import SVR
from sklearn.ensemble import RandomForestRegressor,GradientBoostingRegressor
from xgboost import XGBRegressor